import * as types from "./types"

const printJobRequest: types.IppMessage = {
    type: "IppRequest",
    versionNumber: { minor: 0x01, major: 0x01 },
    operationId: 0x0002,
    requestId: 0x00000001,
    attributeGroup: [
        {
            type: "AttributeGroup",
            beginAttributeGroupTag: 0x01,
            attribute: [
                {
                    type: "Attribute",
                    attributeWithOneValue: {
                        type: "AttributeWithOneValue",
                        valueTag: 0x47,
                        nameLength: 0x0012,
                        name: "attributes-charset",
                        valueLength: 0x0005,
                        value: "utf-8",
                    },
                    additionalValue: []
                },
                {
                    type: "Attribute",
                    attributeWithOneValue: {
                        type: "AttributeWithOneValue",
                        valueTag: 0x48,
                        nameLength: 0x001b,
                        name: "attributes-natural-language",
                        valueLength: 0x0005,
                        value: "en-us",
                    },
                    additionalValue: []
                },
                {
                    type: "Attribute",
                    attributeWithOneValue: {
                        type: "AttributeWithOneValue",
                        valueTag: 0x45,
                        nameLength: 0x000b,
                        name: "printer-uri",
                        valueLength: 0x002c,
                        value: "ipp://printer.example.com/ipp/print/pinetree",
                    },
                    additionalValue: []
                },
                {
                    type: "Attribute",
                    attributeWithOneValue: {
                        type: "AttributeWithOneValue",
                        valueTag: 0x42,
                        nameLength: 0x0008,
                        name: "job-name",
                        valueLength: 0x0006,
                        value: "foobar",
                    },
                    additionalValue: []
                },
                {
                    type: "Attribute",
                    attributeWithOneValue: {
                        type: "AttributeWithOneValue",
                        valueTag: 0x22,
                        nameLength: 0x0016,
                        name: "ipp-attribute-fidelity",
                        valueLength: 0x0001,
                        value: 0x01,
                    },
                    additionalValue: []
                },
            ]
        },
        {
            type: "AttributeGroup",
            beginAttributeGroupTag: 0x02,
            attribute: [
                {
                    type: "Attribute",
                    attributeWithOneValue: {
                        type: "AttributeWithOneValue",
                        valueTag: 0x21,
                        nameLength: 0x0006,
                        name: "copies",
                        valueLength: 0x0004,
                        value: 0x00000014,
                    },
                    additionalValue: []
                },
                {
                    type: "Attribute",
                    attributeWithOneValue: {
                        type: "AttributeWithOneValue",
                        valueTag: 0x44,
                        nameLength: 0x0005,
                        name: "sides",
                        valueLength: 0x0013,
                        value: "two-sided-long-edge",
                    },
                    additionalValue: []
                }
            ]
        }
    ],
    endOfAttributesTag: 0x03,
    data: Buffer.from("%!PDF...")
}
const printJobResponseSuccess: types.IppMessage = {
    versionNumber: 0x0101,
    statusCode: 0x0000,
    requestId: 0x00000001,
    operationAttributesTag: 0x01,
    valueTag: 0x47,
    nameLength: 0x0012,
    name: "attributes-charset",
    valueLength: 0x0005,
    value: "utf-8",
    valueTag: 0x48,
    nameLength: 0x001b,
    name: "attributes-natural-language",
    valueLength: 0x0005,
    value: "en-us",
    valueTag: 0x41,
    nameLength: 0x000e,
    name: "status-message",
    valueLength: 0x000d,
    value: "successful-ok",
    jobAttributesTag: 0x02,
    valueTag: 0x21,
    nameLength: 0x0006,
    name: "job-id",
    valueLength: 0x0004,
    value: 147,
    valueTag: 0x45,
    nameLength: 0x0007,
    name: "job-uri",
    valueLength: 0x0030,
    value: "ipp://printer.example.com/ipp/print/pinetree/147",
    valueTag: 0x23,
    nameLength: 0x0009,
    name: "job-state",
    valueLength: 0x0004,
    value: 0x0003,
    endOfAttributesTag: 0x03,
}
const printJobResponseFailure: types.IppMessage = {
    versionNumber: 0x0101,
    statusCode: 0x040b,
    requestId: 0x00000001,
    operationAttributesTag: 0x01,
    valueTag: 0x47,
    nameLength: 0x0012,
    name: "attributes-charset",
    valueLength: 0x0005,
    value: "utf-8",
    valueTag: 0x48,
    nameLength: 0x001b,
    name: "attributes-natural-language",
    valueLength: 0x0005,
    value: "en-us",
    valueTag: 0x41,
    nameLength: 0x000e,
    name: "status-message",
    valueLength: 0x002f,
    value: "client-error-attributes-or-values-not-supported",
    unsupportedAttributesTag: 0x05,
    valueTag: 0x21,
    nameLength: 0x0006,
    name: "copies",
    valueLength: 0x0004,
    value: 0x00000014,
    valueTag: 0x10,
    nameLength: 0x0005,
    name: "sides",
    valueLength: 0x0000,
    endOfAttributesTag: 0x03,
}
const printJobResponseSuccessWithAttributesIgnored: types.IppMessage = {
    versionNumber: 0x0101,
    statusCode: 0x0001,
    requestId: 0x00000001,
    operationAttributesTag: 0x01,
    valueTag: 0x47,
    nameLength: 0x0012,
    name: "attributes-charset",
    valueLength: 0x0005,
    value: "utf-8",
    valueTag: 0x48,
    nameLength: 0x001b,
    name: "attributes-natural-language",
    valueLength: 0x0005,
    value: "en-us",
    valueTag: 0x41,
    nameLength: 0x000e,
    name: "status-message",
    valueLength: 0x002f,
    value: "successful-ok-ignored-or-substituted-attributes",
    unsupportedAttributesTag: 0x05,
    valueTag: 0x21,
    nameLength: 0x0006,
    name: "copies",
    valueLength: 0x0004,
    value: 0x00000014,
    valueTag: 0x10,
    nameLength: 0x0005,
    name: "sides",
    valueLength: 0x0000,
    jobAttributesTag: 0x02,
    valueTag: 0x21,
    nameLength: 0x0006,
    name: "job-id",
    valueLength: 0x0004,
    value: 147,
    valueTag: 0x45,
    nameLength: 0x0007,
    name: "job-uri",
    valueLength: 0x0030,
    value: "ipp://printer.example.com/ipp/print/pinetree/147",
    valueTag: 0x23,
    nameLength: 0x0009,
    name: "job-state",
    valueLength: 0x0004,
    value: 0x0003,
    endOfAttributesTag: 0x03,
}
const printUriRequest: types.IppMessage = {
    versionNumber: 0x0101,
    operationId: 0x0003,
    requestId: 0x00000001,
    operationAttributesTag: 0x01,
    valueTag: 0x47,
    nameLength: 0x0012,
    name: "attributes-charset",
    valueLength: 0x0005,
    value: "utf-8",
    valueTag: 0x48,
    nameLength: 0x001b,
    name: "attributes-natural-language",
    valueLength: 0x0005,
    value: "en-us",
    valueTag: 0x45,
    nameLength: 0x000b,
    name: "printer-uri",
    valueLength: 0x002c,
    value: "ipp://printer.example.com/ipp/print/pinetree",
    valueTag: 0x45,
    nameLength: 0x000c,
    name: "document-uri",
    valueLength: 0x0019,
    value: "ftp://foo.example.com/foo",
    valueTag: 0x42,
    nameLength: 0x0008,
    name: "job-name",
    valueLength: 0x0006,
    value: "foobar",
    jobAttributesTag: 0x02,
    valueTag: 0x21,
    nameLength: 0x0006,
    name: "copies",
    valueLength: 0x0004,
    value: 0x00000001,
    endOfAttributesTag: 0x03,
}
const createJobRequest: types.IppMessage = {
    versionNumber: 0x0101,
    operationId: 0x0005,
    requestId: 0x00000001,
    operationAttributesTag: 0x01,
    valueTag: 0x47,
    nameLength: 0x0012,
    name: "attributes-charset",
    valueLength: 0x0005,
    value: "utf-8",
    valueTag: 0x48,
    nameLength: 0x001b,
    name: "attributes-natural-language",
    valueLength: 0x0005,
    value: "en-us",
    valueTag: 0x45,
    nameLength: 0x000b,
    name: "printer-uri",
    valueLength: 0x002c,
    value: "ipp://printer.example.com/ipp/print/pinetree",
    endOfAttributesTag: 0x03,
}
const createJobRequestWithCollectionAttributes: types.IppMessage = {
    versionNumber: 0x0101,
    operationId: 0x0005,
    requestId: 0x00000001,
    operationAttributesTag: 0x01,
    valueTag: 0x47,
    nameLength: 0x0012,
    name: "attributes-charset",
    valueLength: 0x0005,
    value: "utf-8",
    valueTag: 0x48,
    nameLength: 0x001b,
    name: "attributes-natural-language",
    valueLength: 0x0005,
    value: "en-us",
    valueTag: 0x45,
    nameLength: 0x000b,
    name: "printer-uri",
    valueLength: 0x002c,
    value: "ipp://printer.example.com/ipp/print/pinetree",
    valueTag: 0x34,
    nameLength: 0x0009,
    name: "media-col",
    valueLength: 0x0000,
    valueTag: 0x4a,
    nameLength: 0x0000,
    valueLength: 0x000a,
    value(memberName): "media-size",
    memberValueTag: 0x34,
    nameLength: 0x0000,
    memberValueLength: 0x0000,
    valueTag: 0x4a,
    nameLength: 0x0000,
    valueLength: 0x000b,
    value(memberName): "x-dimension",
    memberValueTag: 0x21,
    nameLength: 0x0000,
    memberValueLength: 0x0004,
    memberValue: 0x00005208,
    valueTag: 0x4a,
    nameLength: 0x0000,
    valueLength: 0x000b,
    value(memberName): "y-dimension",
    memberValueTag: 0x21,
    nameLength: 0x0000,
    memberValueLength: 0x0004,
    memberValue: 0x00007404,
    endValueTag: 0x37,
    endNameLength: 0x0000,
    endValueLength: 0x0000,
    valueTag: 0x4a,
    nameLength: 0x0000,
    valueLength: 0x000a,
    value(memberName): "media-type",
    memberValueTag: 0x44,
    nameLength: 0x0000,
    memberValueLength: 0x000a,
    memberValue: "stationery",
    endValueTag: 0x37,
    endNameLength: 0x0000,
    endValueLength: 0x0000,
    endOfAttributesTag: 0x03,
}
const getJobsRequest: types.IppMessage = {
    versionNumber: 0x0101,
    operationId: 0x000a,
    requestId: 0x0000007b,
    operationAttributesTag: 0x01,
    valueTag: 0x47,
    nameLength: 0x0012,
    name: "attributes-charset",
    valueLength: 0x0005,
    value: "utf-8",
    valueTag: 0x48,
    nameLength: 0x001b,
    name: "attributes-natural-language",
    valueLength: 0x0005,
    value: "en-us",
    valueTag: 0x45,
    nameLength: 0x000b,
    name: "printer-uri",
    valueLength: 0x002c,
    value: "ipp://printer.example.com/ipp/print/pinetree",
    valueTag: 0x21,
    nameLength: 0x0005,
    name: "limit",
    valueLength: 0x0004,
    value: 0x00000032,
    valueTag: 0x44,
    nameLength: 0x0014,
    name: "requested-attributes",
    valueLength: 0x0006,
    value: "job-id",
    valueTag: 0x44,
    nameLength: 0x0000,
    valueLength: 0x0008,
    value: "job-name",
    valueTag: 0x44,
    nameLength: 0x0000,
    valueLength: 0x000f,
    value: "document-format",
    endOfAttributesTag: 0x03,
}
const getJobsResponse: types.IppMessage = {
    versionNumber: 0x0101,
    statusCode: 0x0000,
    requestId: 0x0000007b,
    operationAttributesTa: 0x01,
    valueTag: 0x47,
    nameLength: 0x0012,
    name: "attributes-charset",
    valueLength: 0x0005,
    value: "utf-8",
    valueTag: 0x48,
    nameLength: 0x001b,
    name: "attributes-natural-language",
    valueLength: 0x0005,
    value: "en-us",
    valueTag: 0x41,
    nameLength: 0x000e,
    name: "status-message",
    valueLength: 0x000d,
    value: "successful-ok",
    jobAttributesTag: 0x02,
    valueTag: 0x21,
    nameLength: 0x0006,
    name: "job-id",
    valueLength: 0x0004,
    value: 147,
    valueTag: 0x36,
    nameLength: 0x0008,
    name: "job-name",
    valueLength: 0x000c,
    subValueLength: 0x0005,
    value: "fr-ca",
    subValueLength: 0x0003,
    name: "fou",
    jobAttributesTag: 0x02,
    jobAttributesTag: 0x02,
    valueTag: 0x21,
    nameLength: 0x0006,
    name: "job-id",
    valueLength: 0x0004,
    value: 148,
    valueTag: 0x36,
    nameLength: 0x0008,
    name: "job-name",
    valueLength: 0x0012,
    subValueLength: 0x0005,
    value: "de-CH",
    subValueLength: 0x0009,
    name: "isch guet",
    endOfAttributesTag: 0x03,
}

export {
    printJobRequest,
    printJobResponseSuccess,
    printJobResponseFailure,
    printJobResponseSuccessWithAttributesIgnored,
    printUriRequest,
    createJobRequest,
    createJobRequestWithCollectionAttributes,
    getJobsRequest,
    getJobsResponse
}